-- ============================================================
-- Screening cáncer de pulmón — proyecto Supabase separado e independiente
-- de Gestión Médica. Datos anónimos (sin nombre/DNI), compartidos entre
-- el cirujano y la neumonóloga: cualquier usuario autenticado lee y escribe.
-- Un documento = un estudio (TC). Varios estudios del mismo paciente se
-- enlazan por "code" (código anónimo derivado del DNI, hasheado en el cliente).
-- ============================================================

create table if not exists casos_screening (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),

  -- identificación anónima
  code text not null,
  prof text,               -- "Cirujano" / "Neumonóloga": quién cargó el caso
  ts timestamptz not null,
  study_date date,
  sex text,
  age integer,
  py numeric,              -- pack-years

  -- riesgo PLCOm2012
  risk numeric,
  level text,
  elig boolean,

  -- factores de riesgo
  cur integer, copd integer, pcan integer, fam integer,
  bmi numeric, cpd numeric, dur numeric, quit numeric,

  -- TC / Lung-RADS v2022
  lr text, lr_name text, nd_type text,
  diam numeric, solid numeric, smod integer,

  -- procedimiento / anatomía patológica (si ya se completó)
  proc text, biopsy_type text, surgery_type text, approach text, proc_date date,
  path_result text, benign_dx text, histo_type text, grade text, margin text,

  -- estadificación TNM 9ª edición
  t_cat text, n_cat text, m_cat text, stage text,

  -- evolución longitudinal respecto al estudio previo del mismo paciente
  study_n integer, days_since integer, d_diam numeric, evol text,
  prev_lr text, prev_diam numeric
);

create index if not exists casos_screening_code_idx on casos_screening(code);

alter table casos_screening enable row level security;

-- Cualquier usuario logueado (cirujano o neumonóloga) puede leer, cargar y borrar casos.
-- No hay separación por médico: los datos son compartidos entre los dos consultorios.
create policy "authenticated_full_access_casos_screening"
  on casos_screening for all
  to authenticated
  using (true)
  with check (true);
